# fly.toml app configuration file generated for reaction-checker on 2023-07-17T14:07:25+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reaction-checker"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
